### ISSUE TITLE
usage give : uninitialized constant

### ISSUE THREAD

**Issue by docop** [barsoom/banktools-global#1]
HI  So it look a great project and perhaps faster than going to iban website to check. But while i did run ruby 2.5, then : 
gem install banktools-global     i enter with : irb  , then put the message as example: 
account = BankTools::Global::IBAN.new(" GB82 WEST 1234 5698 765432 ")
  : But then i got error as : uninitialized constant BankTools .  
i did install the other one ruby: iban-tools and it give the result.  So is there an extra setup needed ?

thanks in advance

**Comment by olleolleolle** [comment]
👋 Hope this helps:

```ruby
require 'banktools/global'
account = BankTools::Global::IBAN.new(" GB82 WEST 1234 5698 765432 ")
```

**Comment by docop** [comment]
So indeed the 'required' did help. I did reinstall ruby, now v2.7.2 , install the full "Development Tools" , also install rails.  So running as your example :
irb
require 'banktools/global'
account = BankTools::Global::IBAN.new(" GB82 WEST 1234 5698 765432 ")
i got only this result: 
 => #<BankTools::Global::IBAN:0x00000000027bdf48 @pre_normalized="GB82WEST12345698765432">

i also try  banktools-se  but give the same end. Not sure what might be missing. thanks

**Comment by olleolleolle** [comment]
I will refer to the Usage section of the README document: https://github.com/barsoom/banktools-global#usage for further usage notes for this gem. Hope this helps!
